name: Publish Docker Image
description: Publish Docker Image with Datetime Tag
inputs:
  dockerhub-username:
    required: true
    description: The user name used to log in to Docker Hub
  dockerhub-password:
    required: true
    description: The password used to log in to Docker Hub
  context:
    required: true
    description: The context used for docker image build
  image-name:
    required: true
    description: The image name to publish
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}
    - name: Generate datetime tag
      id: generate-datetime-tag
      shell: bash
      run: |
        echo "::set-output name=tag::"$(date --iso-8601)""
    - name: Push new docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        tags: |
          ${{ inputs.image-name }}:${{ steps.generate-datetime-tag.outputs.tag }}
          ${{ inputs.image-name }}:latest
