name: Docker Image Publish

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:

  publish-cp-algorithm:
    name: Publish Docker image `cp-algorithm`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/publish-docker-image
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: cp-algorithm
          image-name: xirc/cp-algorithm

  publish-sbt-scala:
    name: Publish Docker image `sbt-scala`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/publish-docker-image
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: sbt-scala
          image-name: xirc/sbt-scala
