name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Build the Docker image (cp-algorithm)
      run: docker build cp-algorithm --tag cp-algorithm:$(date +%s)
    - 
      name: Build the Docker image (sbt-scala)
      run: docker build sbt-scala --tag sbt-scala:$(date +%s)
